---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: 'Tridentオペレータは、の属性を使用して、Astra Tridentのインストール方法をカスタマイズできます `TridentOrchestrator` 仕様' 
---
= Trident オペレータの環境をカスタマイズ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Tridentオペレータは、の属性を使用して、Astra Tridentのインストール方法をカスタマイズできます `TridentOrchestrator` 仕様

属性のリストについては、次の表を参照してください。

[cols="3"]
|===
| パラメータ | 説明 | デフォルト 


| `namespace` | Astra Trident をインストールするネームスペース | デフォルト 


| `debug` | Astra Trident のデバッグを有効にします | いいえ 


| `IPv6` | IPv6 経由の Astra Trident をインストール | いいえ 


| `k8sTimeout` | Kubernetes 処理のタイムアウト | 30 秒 


| `silenceAutosupport` | AutoSupport バンドルをネットアップに自動的に送信しない | いいえ 


| `enableNodePrep` | ワーカーノードの依存関係を自動的に管理（ * beta * ） | いいえ 


| `autosupportImage` | AutoSupport テレメトリのコンテナイメージ | 「 NetApp/trident-autosupport ： 21.04.0 」 


| `autosupportProxy` | AutoSupport テレメトリを送信するプロキシのアドレス / ポート | "http://proxy.example.com:8888"[] 


| `uninstall` | Astra Trident のアンインストールに使用するフラグ | いいえ 


| `logFormat` | Astra Trident のログ形式が使用 [text 、 JSON] | テキスト（ Text ） 


| `tridentImage` | インストールする Astra Trident イメージ | 「 NetApp / Trident ： 21.04 」 


| `imageRegistry` | 形式の内部レジストリへのパス
`<registry FQDN>[:port][/subpath]` | "k83.gcr.io/sig-storage (k8s 1.19+)またはQua.io/k8scsi" 


| `kubeletDir` | ホスト上の kubelet ディレクトリへのパス | 「 /var/lib/kubelet 」 


| `wipeout` | Astra Trident を完全に削除するために削除するリソースのリスト |  


| `imagePullSecrets` | 内部レジストリからイメージをプルするシークレット |  


| `controllerPluginNodeSelector` | Trident Controller CSI プラグインを実行しているポッドの追加ノードセレクタ。pod.spec.nodeSelector と同じ形式を使用します。 | デフォルトはありません。オプションです 


| `controllerPluginTolerations` | Trident Controller CSI プラグインを実行しているポッドに対する許容値を上書きします。POD .spec.Toleratations と同じ形式を使用します。 | デフォルトはありません。オプションです 


| `nodePluginNodeSelector` | Trident ノード CSI プラグインを実行しているポッドの追加ノードセレクタ。pod.spec.nodeSelector と同じ形式を使用します。 | デフォルトはありません。オプションです 


| `nodePluginTolerations` | Trident Node CSI プラグインを実行しているポッドに対する許容値を上書きします。POD .spec.Toleratations と同じ形式を使用します。 | デフォルトはありません。オプションです 
|===

IMPORTANT: `spec.namespace` は、で指定します `TridentOrchestrator` どのネームスペースAstra Tridentがにインストールされているかを示します。このパラメータ * は、 Astra Trident のインストール後に更新できません * 。これを実行すると、のステータスがになります `TridentOrchestrator` に変更します `Failed`。Astra Trident は、ネームスペース間での移行を意図したものではありません。


TIP: ポッドパラメータの書式設定の詳細については、を参照してください link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["ポッドをノードに割り当てます"^]。

上記の属性は、を定義するときに使用できます `TridentOrchestrator` をクリックして、インストールをカスタマイズします。次に例を示します。

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
次に、ノードセレクタを使用して Trident を導入する例を示します。

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
インストールのカスタマイズを検討している場合は、それ以上にカスタマイズする必要があります `TridentOrchestrator` arguments allow、の使用を検討する必要があります `tridentctl` 必要に応じて変更できるカスタムYAMLマニフェストを生成します。
