---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: Trident 環境で Element バックエンドを作成して使用する方法について説明します。 
---
= ONTAP ドライバ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Astra Trident は、 ONTAP クラスタとの通信に使用する 5 つの ONTAP ストレージドライバを提供します。各ドライバーがボリュームの作成、アクセス制御、機能をどのように処理するかについて、詳細をご覧ください。

[cols="5"]
|===
| ドライバ | プロトコル | ボリュームモード | サポートされているアクセスモード | サポートされるファイルシステム 


| `ontap-nas`  a| 
NFS
 a| 
ファイルシステム
 a| 
RWO 、 RWX 、 ROX
 a| 
"" 、 NFS です



| `ontap-nas-economy`  a| 
NFS
 a| 
ファイルシステム
 a| 
RWO 、 RWX 、 ROX
 a| 
"" 、 NFS です



| `ontap-nas-flexgroup`  a| 
NFS
 a| 
ファイルシステム
 a| 
RWO 、 RWX 、 ROX
 a| 
"" 、 NFS です



| `ontap-san`  a| 
iSCSI
 a| 
ブロック
 a| 
RWO 、 ROX 、 RWX
 a| 
ファイルシステムがありません。raw ブロックデバイスです



| `ontap-san`  a| 
iSCSI
 a| 
ファイルシステム
 a| 
RWO 、 ROX
 a| 
`xfs`、 `ext3`、 `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
ブロック
 a| 
RWO 、 ROX 、 RWX
 a| 
ファイルシステムがありません。raw ブロックデバイスです



| `ontap-san-economy`  a| 
iSCSI
 a| 
ファイルシステム
 a| 
RWO 、 ROX
 a| 
`xfs`、 `ext3`、 `ext4`

|===

NOTE: ONTAP バックエンドは、セキュリティロール（ユーザ名とパスワード）のログインクレデンシャル、または ONTAP クラスタにインストールされている秘密鍵と証明書を使用して認証されます。を使用して既存のバックエンドを更新し、認証モードを移行することができます `tridentctl update backend`。
